# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|
 config.ssh.username = 'ubuntu'
 config.ssh.private_key_path = 'must.be.changed'
 config.vm.provider :openstack do |os, override|
   os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
   os.openstack_auth_url = ENV['OS_AUTH_URL']
   os.domain_name = ENV['OS_DOMAIN_NAME']
   os.username = ENV['OS_USERNAME']
   os.password = ENV['OS_PASSWORD']
   os.tenant_name = ENV['OS_TENANT_NAME']
   os.project_name = ENV['OS_PROJECT_NAME']
   os.keypair_name = ENV['OS_KEY_PAIR_NAME']
   os.region = ENV['OS_REGION_NAME']
   os.image = ENV['OS_IMAGE']
 end
 config.vm.define 'linux-server-1' do |s|
     s.vm.provider :openstack do |os, override|
       os.server_name = 'RMENACHO-DH01'
       os.flavor = ENV['OS_FLAVOR']
       override.vm.synced_folder '.', '/vagrant', disabled: true
     end
 end
 config.vm.define 'jenkins_server' do |s|
     s.vm.provision 'docker'
     s.vm.provision 'docker_compose', compose_version:'1.23.2'
     s.vm.provision "shell", path: "./install-jenkins.sh"
     s.vm.provider :openstack do |os, override|
       os.server_name = 'RMENACHO-DH02'
       os.flavor = ENV['OS_FLAVOR']
       override.vm.synced_folder '.', '/vagrant', disabled: true
     end
 end

 config.vm.synced_folder "./docker", "/home/ubuntu/docker"
 config.vm.define 'jenkins_server_2' do |s|
     s.vm.provision 'docker'
     s.vm.provision "shell", path: "./install-jenkins-dc.sh"
     s.vm.provision 'docker_compose', compose_version:'1.23.2', yml: '/home/ubuntu/docker/docker-compose.yml', rebuild: true, run: 'always'
     s.vm.provider :openstack do |os, override|
       os.server_name = 'RMENACHO-DH03'
       os.flavor = ENV['OS_FLAVOR']
       override.vm.synced_folder '.', '/vagrant', disabled: true
     end
 end
end

